### ISSUE TITLE
Error: different `language` found in DESCRIPTION

### ISSUE THREAD

**Issue by rempsyc** [inbo/checklist#100]
I always get the same error regardless of the function I use, `Error: different 'language' found in DESCRIPTION`. I tried `checklist::setup_package()` for a new package.

```r
> checklist::setup_package()
No `checklist.yml` found. Assuming this is a project.
Error: different `language` found in DESCRIPTION
```

My description file has the following language information:

```r
Encoding: UTF-8
Language: en-US
```

Anything I'm missing? Here is my description file: https://github.com/rempsyc/report/blob/main/DESCRIPTION

**Comment by ThierryO** [comment]
This should be fixed in the upcoming version 0.3.0. See #94 .
