### ISSUE TITLE
Spelling check marks unwanted items from roxygen documentation

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#102]
After running `checklist::check_spelling()` locally in a package that is written in dutch language, some words typical for roxygen documentation are (in my opinion incorrectly) marked as spelling mistakes:
- `@return`
- `\itemize` and `\item` (used to layout a list)
- `\eqn` and items inside `{}{}` following  `\eqn` (in this case `\sim`, `B\log`, `C\log`, `+`, `\delta` and `B.log`, but it would be good to ignore everything between the two pairs of `{}`, I think)

Is there a way to mute this, other than adding these items as words to the `.dic` file?

**Comment by ThierryO** [comment]
The internal function `spelling_parse_r()` should strip [`@return`](https://github.com/inbo/checklist/blob/47bd3e08a2e09d2a7356bb40bfb5fa75b0f035d0/R/spelling_parse.R#L38) and [`\eqn()`](https://github.com/inbo/checklist/blob/47bd3e08a2e09d2a7356bb40bfb5fa75b0f035d0/R/spelling_parse.R#L76).

I prefer to use markdown syntax over latex syntax in Roxygen comments. It makes the documentation source easier to read.

**Comment by ElsLommelen** [comment]
Note for others with a similar issue: `\eqn()` is only stripped when the whole equation is set on one line.
