### ISSUE TITLE
Use `bibentry` not `citEntry`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/checklist#106]
Found in rOpenSci news:

> New CRAN guideline on CITATION file
> CRAN requires CITATION files to be declared as [`bibentry` items](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/bibentry.html), and not in the previously-accepted form of [`citEntry()`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/citEntry.html). As an example see [the dynamite CITATION file](https://github.com/ropensci/dynamite/blob/main/inst/CITATION) which refers to the R manual as well as other associated publications.

**Comment by ThierryO** [comment]
fixed in [4f53ca8](https://github.com/inbo/checklist/pull/104/commits/4f53ca83622dab78a701e632002a06ac2887845f)
