### ISSUE TITLE
Relax INBO affiliation string

### ISSUE THREAD

**Issue by florisvdh** [inbo/checklist#112]
Currently required affiliation string for INBO personnel:

`Research Institute for Nature and Forest (INBO)`

I propose to also allow `Research Institute for Nature and Forest`, since this is more in line with general affiliation formats.

**Comment by ThierryO** [comment]
`checklist` enforces the official names. They include `(INBO)`. Hence we should not relax the affiliation string.

**Comment by ThierryO** [comment]
The communication team adds it because there is otherwise no link between the English name and inbo.be.
