### ISSUE TITLE
`check_spelling()` does not use all words in dictionary

### ISSUE THREAD

**Issue by wlangera** [inbo/checklist#121]
When I run the `check_spelling()` function, I get messages that `'feitelijke'` and `landbouwcijfers.vlaanderen.be` are not in my dictionary.

![image](https://github.com/inbo/checklist/assets/60934857/1bdf108e-34e8-4af8-a246-a99e7f225ca3)

But this is not true:

![image](https://github.com/inbo/checklist/assets/60934857/8a74fce4-5cb7-488b-9b7b-d498cb0ef983)

I am not sure why. I have tried to quote (') other words, but there it works. So I am not sure if special characters are the cause.
`landbouwcijfers.vlaanderen.be`  is uses as such in my markdown file:

```
[landbouwcijfers.vlaanderen.be](https://landbouwcijfers.vlaanderen.be/open-geodata-landbouwgebruikspercelen)
```

I was unable to debug this (got stuck at the function `R_hunspell_info()`).

**Comment by ThierryO** [comment]
Use double quotes instead of single quotes.
checklist considers single quotes as apostrophes.

landbouwcijfers.vlaanderen.be is not a word but an url.
Use either

    [https://landbouwcijfers.vlaanderen.be](https://landbouwcijfers.vlaanderen.be/open-geodata-landbouwgebruikspercelen)
    [Vlaamse landbouw en visserij in cijfers](https://landbouwcijfers.vlaanderen.be/open-geodata-landbouwgebruikspercelen)

**Comment by wlangera** [comment]
Thank you. Solved!
