### ISSUE TITLE
Similar package

### ISSUE THREAD

**Issue by csgillespie** [inbo/checklist#13]
Hi. Really like your package and approach. 

Just to note that https://github.com/jumpingrivers/inteRgrate does similar things (in a different way)

**Comment by ThierryO** [comment]
@csgillespie this package was inspired by your talk at eRUM ;-)

**Comment by csgillespie** [comment]
Cool. I like your yaml file idea - I might "borrow" it ;)

I went down environment variables because we use gitlab-ci mainly and you can set a variable at the organisation level. That way you would avoid each repo having a yaml file. But this doesn't work under github :(

**Comment by ThierryO** [comment]
A `checklist.yml` is not always required. If it [not present](https://github.com/inbo/checklist/blob/9e3c16a1ad17db018a71d0ba8fb782a33028bdb5/R/read_checklist.R#L17), we assume you're checking a package without allowed warnings or notes. So you only need a `checklist.yml` if it's not a package, or when the package needs to deviate from the standard.

Github allows to to set "secrets" at repo and organisation levels. They are available when you run [github actions](https://github.com/inbo/checklist/blob/master/.github/workflows/check_on_master.yml). You'll find them under "settings".
