### ISSUE TITLE
Error: different `language` found in DESCRIPTION

### ISSUE THREAD

**Issue by adamhsparks** [inbo/checklist#137]
Using `setup_package()` results in this error. I found this issue, https://github.com/inbo/checklist/issues/100, that's a year old and says it's fixed.

My DESCRIPTION has

```
Encoding: UTF-8
Language: en-AU
```

It does the same with `en-US` as well.

**Comment by ThierryO** [comment]
Thank you for the feedback. Could you share your code or reproducible example? That would simplify my debugging work.

**Comment by ThierryO** [comment]
Can you test the version in the codeowners branch? `remotes::install_github("inbo/checklist@codeowners")`. The code only tested with `en-GB`, `nl-BE` and  `fr-FR`. Spell checking might not work with other variants of these languages. Installing the correct hunspell dictionary should be sufficient. Non spellcheck functions should not be affected.

**Comment by adamhsparks** [comment]
Ah. I’ll check. Mine would be en-AU
