### ISSUE TITLE
README getting started instructions are unclear to me

### ISSUE THREAD

**Issue by adamhsparks** [inbo/checklist#138]
Glancing over the README I tried to follow the instructions given but it ends with errors, so I had to dig further into the vignettes to find the proper steps, which also resulted in an error for the other issue I've opened.

After following the install instructions, I followed the next steps but get an error.

```r
library(checklist)
check_package()

Checking spelling
Error:
! no checklist.yml found `.` or its parents
Show Traceback
```

**Comment by ThierryO** [comment]
Good catch. In the past you could run the checks without setting checklist up. I need to update the README and make the error message more clear.

**Comment by ThierryO** [comment]
I've update the [README](https://github.com/inbo/checklist/tree/codeowners). Could you please give me feedback on this version?

**Comment by adamhsparks** [comment]
Thanks for the updates. This really does seem useful, even outside INBO.

However, I'm still running into errors when I follow the README.

After installing, I load the library and create my own org like so.

```r
> library(checklist)
> org <- organisation$new(
+   github = "AAGI-Org-AU-Public",
+   community = NA_character_,
+   email = "adam.sparks@curtin.edu.au",
+   rightsholder = "Grains Research and Development Corporation (GRDC), Curtin University, The University of Queensland, University of Adelaide",
+   funder = "Grains Research and Development Corporation (GRDC), Curtin University of Technology, The University of Queensland, University of Adelaide",
+   organisation = list(
+     "Curtin University" = list(affiliation = "Curtin University", orcid = TRUE)
+   )
+ )
```

When I then try to set the default org, I get an error.

```r
> default_organisation(org = org)
Error in file(file, "w", encoding = fileEncoding) : 
  cannot open the connection
In addition: Warning message:
In file(file, "w", encoding = fileEncoding) :
  cannot open file '/Users/283204f/Library/Preferences/org.R-project.R/R/checklist/organisation.yml': No such file or directory
```

**Comment by ThierryO** [comment]
That might be a bug in `default_organisation()`. I presume it is because the folder `/Users/283204f/Library/Preferences/org.R-project.R/R/checklist` doesn't exist on your machine. Could you try the code below. If that works, then I know to fix the issue.

```
dir.create(R_user_dir("checklist", which = "config"))
default_organisation(org = org)
```

**Comment by adamhsparks** [comment]
Prefixing `tools::` works locally.

Then the `default_organisation(org = org)` is able to be set.

```r
dir.create(tools::R_user_dir("checklist", which = "config"))
default_organisation(org = org)
```
