### ISSUE TITLE
license doesn't match versus ugly NA in website

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#139]
After setting up the checklist functionality on an existing package using `setup_package()`, I get the error that LICENSE.md doesn't match the version in the checklist package (because I took my version somewhere else).  The differences seem to be just layout differences, such as headers that are one level lower, no bold in text, newline at different place,...  I don't care too much to change the layout, but the major drawback of using the checklist style licence, is the ugly NA that appears in [the pkgdown website](https://inbo.github.io/checklist/LICENSE.html) due to the absence of a title or a first level header in the `LICENSE.md` file.  On the other hand, muting the error does not guarantee that the content of the licence is the same (and I want to mute as few as possible).  So it is difficult to choose, and it would be nice if the standard layout of the license could lead to a nice website.  (In a previous package, I apparently didn't do the effort to mute this remark, because I always notice it only in the end when I'm tired of solving remarks, which is a pity.)

**Comment by ThierryO** [comment]
I've updated the licenses so they all start with a level 1 heading. checking the package will update the license when it is not matching.
