### ISSUE TITLE
create_package: suggestions for CONTRIBUTING file

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#15]
When reading the file `CONTRIBUTING.md` generated when using function `create_package()`, I noticed the last line refers to the 'git2rdata project'.  Would it be possible to add the package name of the newly created package here (instead of 'git2rdata')?  Another option would be to just omit 'git2rdata' and refer to 'this package'.

Also, in the section `Fixing typos` in this file, personally I think the wording with YES and NO reads rather difficult.  It would be much shorter and straightforward to write it in one sentence such as ``E.g. edit a roxygen comment in a `.R` file below `R/`, not in an `.Rd` file below `man/`.``

**Comment by ThierryO** [comment]
Goog suggestions. Would you send a PR into the 0.1.5 branch?

**Comment by ThierryO** [comment]
Solved in #27
