### ISSUE TITLE
suggestion for documentation create_package()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#16]
After generating a package using `create_package()`, a package with a lot of files is created: 

- some of them are not meant to be changed at all (e.g. LICENSE.md),
- some have to be changed to avoid nonsense to appear on the package website (e.g. README.Rmd),
- some could be changed dependent on the user's preferences but don't have to (e.g. CONTRIBUTING.md, yml-files, extra.css) and
- some have to be changed while developing code (e.g. DESCRIPTION, NEWS.md)

You can suppose users have some basic knowledge on package development before using this function, so they will hopefully know and recognise most of the files and know when to change them.  But it would certainly be useful if an overview of files of the second category is documented somewhere: the ones that have to be changed for the content but do not cause an error if not changed.

Admittedly, users should check if they agree with the content of all files, which they probably do at first use, but for regular users it would be useful to have an overview to be able to quickly change what they need to.

**Comment by ThierryO** [comment]
I agree we would need better documentation and even a vignette on this topic.

- I'm planning on checking the files that the user shouldn't touch (LICENSE.md, extra.css, CONTRIBUTING.md?...)
- NEWS.md is already checked: it requires an entry for the current version.
- Maybe we could check if the user changed the dummy text in DESCRIPTION and README.Rmd?
