### ISSUE TITLE
License for non package project?

### ISSUE THREAD

**Issue by ThierryO** [inbo/checklist#18]
Should a project with only source files (.R, .Rmd) have a license? IMHO it should.

I'd like to hear your opinion @ElsLommelen @hansvancalster @florisvdh @pietervsd @ToonHub @ToonVanDaele

**Comment by hansvancalster** [comment]
Maybe we can follow the [Zenodo policies](https://about.zenodo.org/policies/):  Licenses: Users must specify a license for all publicly available files. Licenses for closed access files may be specified in the description field.

Zenodo also makes recommendations for type of license to chose from depending on the type of deposit (for instance CC BY for data if I remember well). I think they follow [openaire](https://www.openaire.eu/2018-09-20-14-50-09?highlight=WyJsaWNlbnNlIl0=).

**Comment by ElsLommelen** [comment]
Yes, why not?  You are publishing code openly, so it should be clear in which circumstances it can be used, and you can moreover protect yourself against claims from users that use the code in a wrong way...  It might seem extravagantly to add this for some files of code, but in the end it is a good habit for the (rare?) cases something goes wrong and you need protection.

**Comment by ThierryO** [comment]
In most cases we can do by just adding a LICENSE.md to the root of the repository. The default license for INBO data is CC0. However, data only repos our currently out-of-scope for the checklist package.
Source code repositories (not packages) can have the same licences as packages.

**Comment by florisvdh** [comment]
I fully agree, licensing is about the code, be it a project or a package.
