### ISSUE TITLE
path in setup_package() has no default

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#20]
The documentation of the argument `path` in the function `setup_package()` mentions 'Defaults to `"."`'.  However, when using this function without arguments in an existing package, I get the following error:

``` r
checklist::setup_package()
#> Error in normalizePath(path, winslash = "/", mustWork = TRUE): argument "path" is missing, with no default
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ThierryO** [comment]
Fixed in #27
