### ISSUE TITLE
possibility to ignore certain checks

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#24]
Nice package!  It is easy to add to an existing package and it clearly reports all problems.

I however encounter a problem: in an existing package I did not yet apply the currently used naming conventions and I wish not to change it.  As of the lintr test, I can easily pass it by changing the default linters (to allow camelcase).  As a convention I like using the function name as a file name, but I see no option to pass the `check_filename()` test in this way.  Is it an option to give users any flexibility in using or not using certain tests?

**Comment by ThierryO** [comment]
`check_package()` runs the entire set of checks. If you want to run only some of the checks, then you can run the checks you want and omit the ones you don't want.
