### ISSUE TITLE
file extensions in lower case?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#25]
It could be a good idea to require file extensions in lower case to avoid problems in Linux OS, but it seems very hard to meet this requirement in other OS:
- RStudio automatically uses capitals in extensions in Windows and Mac OS, and there seems to be no option to change this behaviour
- after changing these extensions manually to lower case, these changes are not detected in the git module in RStudio (because it is case insensitive?), so I am not sure how to pass these changes to github...

As this package is mainly written for INBO users, who are generally Windows users, I would suggest doing one of the following:
- write a manual on how to deal with this
- provide a function to change these extensions automatically (locally and on github)
- reconsider the need of this rule

**Comment by florisvdh** [comment]
I'm not sure whether I understand this issue well enough, but for R scripts and Rmd files I believe it is common to use xxx.R and yyy.Rmd (with uppercase 'R'), independent of the platform. I've not observed this to be different in RStudio on Linux.

With regard to Linux: did you encounter problems with file extensions? Generally file extensions don't matter and aren't used in determining the filetype, in Linux OSs.

**Comment by ElsLommelen** [comment]
@florisvdh Eh, small correction (my mistake, I apparently didn't check it thoroughly enough): I only get errors for `.Rd` files with the message that the extension should be in lower case, apparently the `.R` and `.Rmd` files pass if no uppercase is used in the name itself.  But my remark stays the same: I have absolutely no idea how to change the extension of these automatically generated files...  (And I don't feel like doing it manually, it seems not a good idea to require styles that cannot be generated automatically in RStudio.)

(When searching on the internet how to change these extensions to lowercase, I read a comment on the fact that it could cause problems in Linux, but the exact distribution was not specified.  So I supposed this could be a general problem and a reason to require the use of lowercase...)

**Comment by florisvdh** [comment]
For Rd files I guess `.Rd` should always be accepted. The file extension is created like that when running `devtools::document()`.

**Comment by ElsLommelen** [comment]
Should I propose this change in a PR, or should I wait for @ThierryO to agree that it is a problem that should be changed?

**Comment by ElsLommelen** [comment]
Strange thing is: the [news site](https://inbo.github.io/checklist/news/index.html) mentions that `.Rd` is allowed from version 0.1.5 on, and the [code](https://github.com/inbo/checklist/blob/master/R/check_filename.R#L73) indeed seems to allow this, but I still get this error, as well locally (with the latest version installed) as after pushing changes to github.

**Comment by ThierryO** [comment]
The problem is only Windows because that is a case insensitive OS. You can change the filenames on GitHub. I know that it is a cumbersome workaround. But you'll learn fast to use the correct capitalisation ;-)

**Comment by ElsLommelen** [comment]
But as @florisvdh mentions: `devtools::document()` automatically creates `.Rd` with capitals, also in Linux, so it is a bit odd that it is not accepted as such.  And after looking at the news site, I suppose it is meant to be accepted but I still get remarks...

**Comment by ThierryO** [comment]
Can you share the repo where you encounter this? Because it shouldn't.

**Comment by ElsLommelen** [comment]
[Here](https://github.com/inbo/dhcurve/pull/44) the PR with the problem.
