### ISSUE TITLE
Adapt checks in `setup_package()`

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#29]
Is there a possibility to adapt the checks that are set up by using the function `setup_package()`?

I have an existing package and I would like to use package checklist to set up an automated check, but as I used a slightly different style, I would like to omit one of the checks.  Is there any possibility to do so?

Besides package documentation of this package, I also checked the [inbo/actions](https://github.com/inbo/actions) repo, but I don't see any possibility to check for instance all tests but `check_filename()`.  It seems some configuration is possible in `checklist.yml`, but I am not sure if it is also possible to ignore certain checks here (and how)?  Or is it possible to adapt tests by overwriting functions such as `check_filename()` in my own package?

**Comment by ThierryO** [comment]
Feel free to use the checklist package to create custom checks. However, as this goes against the goal of `checklist` to standardise INBO package, we won't provide support.
