### ISSUE TITLE
documentation check_description()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#35]
When running `check_description()` locally, I properly get the error 'Package version not updated', but when running it during CI, this error doesn't show up despite I did not yet update the version number (it is exactly the same situation as I tried locally, see [here](https://github.com/inbo/dhcurve/runs/2166764074) under check description).

I don't know whether or not this is a bug, I may just have used the function in a wrong way, but it would anyway be nice to have some explanation in the help function on how to use it (that includes a way to avoid this problem).

**Comment by ElsLommelen** [comment]
[In this push](https://github.com/inbo/dhcurve/pull/44/checks?check_run_id=2168325954) I added some output such as `repo` and the version number returned by `get_version()`, which confirms that the same head is used locally and on github.  Also the version number is the same.  Maybe this helps to check if it could be a bug?

**Comment by ThierryO** [comment]
Are your local `master` and `origin/master` branch up to date with the version on GitHub?

**Comment by ElsLommelen** [comment]
Yes, they are.  (And they also where when I added the issue: I didn't touch the project afterwards.)

However, the branch in which I added CI, has not been merged to the master yet.  I don't know if this could have an influence?

**Comment by ThierryO** [comment]
I'm closing this issue as you are using checklist not as it is intended. I know and understand your reasons for doing so. However, it goes against the philosophy of checklist. In order to avoid a precendent, I cannot support workarounds.
