### ISSUE TITLE
Files 'README.md' or 'NEWS.md' cannot be checked without 'pandoc' being installed.

### ISSUE THREAD

**Issue by hansvancalster** [inbo/checklist#40]
@ThierryO the issue with `Files 'README.md' or 'NEWS.md' cannot be checked without 'pandoc' being installed.` is a known Windows specific issue: https://github.com/r-lib/rcmdcheck/issues/109

The issue is still open. Is the suggestion to add these files to `.RBuildIgnore` a good one?

_Originally posted by @hansvancalster in https://github.com/inbo/protocolhelper/issues/43#issuecomment-805044417_

**Comment by hansvancalster** [comment]
@ThierryO I can also add the files to the `.RBuildIgnore` of the `protocolhelper` package. In case I do that, will these changes be overwritten by `checklist::setup_package()`?

**Comment by ThierryO** [comment]
`checklist::setup_package()` will only work when the project is under version control and when the git workspace is clean. If you see any modified files after running `checklist::setup_package()`, you know that `checklist::setup_package()` introduced those changes. You can (and should) inspect those changes prior to committing them.

**Comment by ThierryO** [comment]
The [current development](https://github.com/inbo/checklist/blob/0d18e66d841e9da8b67cdbe47972291aa126139d/R/setup_package.R#L43) of `checklist::setup_package()` appends to `.Rbuildignore` rather than overwriting it.
