### ISSUE TITLE
reference/tutorial/vignette on how to create an R project for analysing and reporting data

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#41]
Idea taken from previous PR review on the documentation of `setup_source()`:
 
As `create_source()` does not exist, and users often do not know how such a repo should be organised (I got a question on it last week...), it would be interesting to refer to information on this subject (or some publicly available examples). Or if this is not available, it would be helpful to write a tutorial/vignet on the subject: 'how to create an R project for analyzing and reporting scientific data'.

**Comment by ElsLommelen** [comment]
Are you sure you want to close it already?  You asked me to make this issue some days ago (and preferably add a PR), but I haven't done yet...  So unless you did it, it hasn't been done.

**Comment by ThierryO** [comment]
My mistake.

**Comment by ThierryO** [comment]
fixed in #94
