### ISSUE TITLE
false positive check due to motivation?

### ISSUE THREAD

**Issue by hansvancalster** [inbo/checklist#42]
After [re-running `check-package`](https://github.com/inbo/protocolhelper/pull/43/checks?check_run_id=2435544743) I see this:

  
![image](https://user-images.githubusercontent.com/18713718/116041192-3671b600-a66d-11eb-85dc-997ec0eed68a.png)

but I guess the presence or absence of a motivation should not trigger a new note?

**Comment by ThierryO** [comment]
The quotes in both messages are different. This is a false positive. I'll have a look at it.
