### ISSUE TITLE
option to allow other word delimiters in folder (file) names?

### ISSUE THREAD

**Issue by hansvancalster** [inbo/checklist#43]
I believe it can be quite common to also have `-` in folder names, possibly in combination with `_`. Currently, only `_` is allowed. 

Examples: 

- https://github.com/inbo/protocols#folder-and-filename-syntaxis
    - folder name is `<protocolcode>_<shorttitle>`: e.g. sfp-401-nl_my-short-title
    - if only `_` is allowed this would become sfp_401_nl_my_short_title, which does not read well and is not regexp friendly (for instance the original `<protocolcode>` and `<shorttitle>` can be easily recovered in the former case by splitting the string at `_`)
- Often folder names contain a date as part of their name. The [ISO 8601 standard](https://nl.wikipedia.org/wiki/ISO_8601) is specified using hyphens: `YYYY-MM-DD`. `YYYYMMDD` is a good alternative, but a lot less readable.
-   If folder or filenames also end up as part of URL's, the general advice is to avoid underscores altogether. See for instance https://x-equals.com/dashes-versus-underscores/ (but I won't go as far as to suggest to only use hyphens)
- Many automatically created file and folder names use hyphens.  For instance: when using `rmarkdown` or `bookdown`, figures are written to a folder named `figures-html` and inside that folder figures are names `chunk-name-1.png`. Another example is `usethis::use_test(foo)`, which will write to a folder `testthat/test-foo.R`
- ...

I believe an extra argument to `check_filename()` that states which word delimiters are allowed (default only `_` underscore; and hyphen or both as the only alternatives) would greatly increase the chance that existing repositories consider using the `checklist` package.  

What do others think about this? @inbo/bmk ?

_Originally posted by @hansvancalster in https://github.com/inbo/checklist/pull/38#discussion_r616791097_

**Comment by ThierryO** [comment]
- Keep in mind that you should only test folder names in the source code, not the rendered output. Hence you are free to use what ever folder name you want in the output.
- The regexp for your example is not that more complex (`(.*?_.*?_.*?)_(.*)` vs `(.*)_(.*)`)
- Allows different rules across repositories makes things more complex when working on different repositories. You'll have to remember with rules apply to a specific repository. Having the same rules for every repository makes it easier.

**Comment by hansvancalster** [comment]
> * Keep in mind that you should only test folder names in the source code, not the rendered output. Hence you are free to use what ever folder name you want in the output.

I know, but several of the examples I gave refer to source code.

> * Allows different rules across repositories makes things more complex when working on different repositories. You'll have to remember with rules apply to a specific repository. Having the same rules for every repository makes it easier.

I agree with this completely for R packages (I forgot to mention in the issue that I would not allow this option for R packages, only for source repos). For repositories that only store source code and which are often only used in a project-specific setting, I think more flexibility would be a bonus.

**Comment by ElsLommelen** [comment]
> What do others think about this? @inbo/bmk ?

I'm in favour of using 1 separator.  Certainly for `-` and `_`, I find quite confusing if they are mixed: they look very similar, and I find myself making a lot of mistakes if I for instance have to refer to filenames with both separators mixed together.

**Comment by hansvancalster** [comment]
I just stumbled on this after running `checklist::check_source()`

![image](https://user-images.githubusercontent.com/18713718/117835358-35997080-b278-11eb-8d69-6a162f18a369.png)

So, if we also put the `.Rproj` file under version control (which is often done to make sure everyone has the same Rproj settings), then `checklist` expects the projectname to adhere to the filename conventions. By default, Rstudio will use the GitHub repository name as the projectname. The convention at INBO for repository names is to use a hyphen as separator instead of an underscore (if I remember correctly: @peterdesmet ?).

**Comment by hansvancalster** [comment]
> I just stumbled on this after running `checklist::check_source()`
> 
> ![image](https://user-images.githubusercontent.com/18713718/117835358-35997080-b278-11eb-8d69-6a162f18a369.png)
> 
> So, if we also put the `.Rproj` file under version control (which is often done to make sure everyone has the same Rproj settings), then `checklist` expects the projectname to adhere to the filename conventions. By default, Rstudio will use the GitHub repository name as the projectname. The convention at INBO for repository names is to use a hyphen as separator instead of an underscore (if I remember correctly: @peterdesmet ?).

**Comment by hansvancalster** [comment]
> The convention at INBO for repository names is to use a hyphen as separator instead of an underscore (if I remember correctly: @peterdesmet ?).

@ThierryO it's actually in a tutorial we wrote: [styleguide repos](https://inbo.github.io/tutorials/tutorials/styleguide_repos/). The tutorial advices to use dash instead of underscore (for both directory and file names) and thus contradicts the `checklist` naming convention.

**Comment by ThierryO** [comment]
> > The convention at INBO for repository names is to use a hyphen as separator instead of an underscore (if I remember correctly: @peterdesmet ?).
> 
> @ThierryO it's actually in a tutorial we wrote: [styleguide repos](https://inbo.github.io/tutorials/tutorials/styleguide_repos/). The tutorial advices to use dash instead of underscore (for both directory and file names) and thus contradicts the `checklist` naming convention.

No. The [blame](https://github.com/inbo/tutorials/blame/master/content/tutorials/styleguide_repos/index.md) indicates that OSciBio wrote that document and added you and me as author. I never contributed to that document.
