### ISSUE TITLE
Create INBO pkgdown css

### ISSUE THREAD

**Issue by peterdesmet** [inbo/checklist#48]
See discussion at https://github.com/inbo/watina/issues/15

Should also solve issues of `git2rdata`:

<img width="500" alt="Screenshot 2019-06-04 at 11 38 28" src="https://user-images.githubusercontent.com/600993/65154673-37bc1500-da2c-11e9-90c8-177cb4a19080.png">

**Comment by ThierryO** [comment]
fixed in #53
