### ISSUE TITLE
Why CC-BY-SA as default LICENSE file

### ISSUE THREAD

**Issue by peterdesmet** [inbo/checklist#49]
In https://github.com/inbo/checklist/commit/4892c8ed747174127b14e1e68c2d588cfbc288b1 I noticed that https://creativecommons.org/licenses/by-sa/4.0/ is used as default `LICENSE` file. That is a bit of an odd choice for software. What is the reasoning?

**Comment by ElsLommelen** [comment]
See discussion in #18.  ;-)

**Comment by ElsLommelen** [comment]
Oups, I see this is not really a discussion on which license.  In any way, this commit concerns the function `setup_source()`, which is a function that adds tests to repo's that are not packages, e.g. repo's to produce tutorials or reports.

**Comment by florisvdh** [comment]
I follow the philosophy of making users aware of choices that are made, and of how to alter them.

**Comment by ThierryO** [comment]
`setup_source()` is intended for repos with Rmarkdown reports. I don't consider those to be software. For R packages we use GPL-3.

**Comment by peterdesmet** [comment]
Great! In that case I would suggest CC-BY, similar to what is used for most open access papers.

**Comment by ThierryO** [comment]
The license will depend on the default licence given to all INBO reports. This is being discussed in the internal library working group. For more details contact @hansvancalster.

**Comment by ThierryO** [comment]
**adding a license**

- `setup_source()` now sets the CC-BY license unless there is an existing LICENSE file.
- `create_package()` and `setup_package()` sets a GPL-3 license unless there is an existing LICENSE file.

IMHO one should use `setup_source()` for repos with mainly Rmarkdown reports, or for code used in a report or paper. Hence a CC-BY license seems appropriate. In a case were GPL-3 or MIT would be more appropriate, you probably should write a package.

**checking a license**

- `check_license()` checks if the standard GPL-3 license is present.
- `check_package()` runs `check_description()`, which runs `check_license()`, thus currently enforcing GPL-3 for packages.
- `check_source()` currently does not run `check_license()`, thus does not enforce any license.

MIT is currently not supported. A PR that adds MIT support is welcome.

**Comment by ThierryO** [comment]
Closing this issue as we set CC-BY as default for non-package repositories.

A PR allowing MIT for package is still welcome.
