### ISSUE TITLE
Note because pandoc is not installed

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#55]
When following [this manual](https://inbo.github.io/checklist/articles/getting_started.html#get-it-working-with-an-existing-package-or-update-the-checklist) to install the checks on an existing package (inbodb), I got the following note when running `x <- checklist::check_package()`:
```
N  checking top-level files ...
   Files 'README.md' or 'NEWS.md' cannot be checked without 'pandoc' being installed.
```
When doing the regular checks in RStudio (with or without adding the option `--as-cran`), I don't get this note, so I suppose this remark is coming from checklist?
On the other hand I noticed [on the tutorials website](https://inbo.github.io/tutorials/installation/administrator/admin_install_pandoc/#windows) that pandoc is automatically installed with RStudio, so I should have it installed?

I don't understand why this note is there and it would be good to somewhere in the documentation find some advise on how to deal with it (preferably with a reference to the documentation in the note itself).

**Comment by hansvancalster** [comment]
I've encountered this issue too. See https://github.com/inbo/checklist/issues/40.

**Comment by ElsLommelen** [comment]
What is actually checked in these files?
If it is relevant, I think it's a pity that these tests are also ignored in the Linux tests because we put them in `.Rbuildignore` just because of the note.  I'd rather ignore the note, unfortunately here again we have to choose once for both Windows and Linux.  If relevant, I'd rather suggest a PR to ignore this specific test on Windows machines (if possible).  If it's just a check if the file is present, ignoring is indeed the right thing to do.

**Comment by ThierryO** [comment]
I think that R CMD checks if it can renders those files to html. If you add them to `.Rbuildignore`, they will not be ables on CRAN. So not an issue for packages not on CRAN.
