### ISSUE TITLE
"type" of contributor on Zenodo

### ISSUE THREAD

**Issue by ThierryO** [inbo/checklist#75]
Zenodo requires the "type" of contributor to be defined in `.zenodo.json`. Available options are listed below. We need to pick one to use for people listed in the `DESCRIPTION` with `role = "ctb"`. Which should we pick? Researcher? ProjectMember? Other? Their names will be listed under this title at the Zenodo page of the package.

- ContactPerson
- DataCollector
- DataCurator
- DataManager
- Distributor
- Editor
- Funder
- HostingInstitution
- Producer
- ProjectLeader
- ProjectManager
- ProjectMember
- RegistrationAgency
- RegistrationAuthority
- RelatedPerson
- Researcher
- ResearchGroup,
- RightsHolder
- Supervisor
- Sponsor
- WorkPackageLeader
- Other

**Comment by hansvancalster** [comment]
I'm in favor of "other" since none of the other correspond to contributor.

**Comment by ThierryO** [comment]
Any one else from @inbo/bmk or @inbo/oscibio how has an opinion on this?

**Comment by peterdesmet** [comment]
Yeah, none of the others fit as contributor, so `other`. I’m assuming the `role=“aut”` are listed as authors?

**Comment by florisvdh** [comment]
@ThierryO you used 'ProjectMember' in the above referred example; I would prefer that too. IMO it is what comes closest to the role of 'Contributor' in the list (viewing package development as the project). I'd prefer that over 'Other', which does not give a clue about the role.

**Comment by ThierryO** [comment]
@team_bmk decided to opt for `ProjectMember`
