### ISSUE TITLE
checking CRAN incoming feasibility ... NOTE Maintainer

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#78]
Just an idea, it's not a big deal if this can't be solved.

After solving all errors, warnings and notes for a package, I end up with the note described [here](https://stackoverflow.com/questions/23829978/checking-cran-incoming-feasibility-note-maintainer), and I wonder: if it always appears and if it is only relevant for submitting at cran, could it easily be ignored by default when running the checklist function `check_package()` (during CI), e.g. by adding this note automatically to `checklist.yml`?  Just an idea to save users some time from looking up where this note is about, but if implementing this takes much more effort than users need to ignore this note, feel free to just ignore this issue.

**Comment by ThierryO** [comment]
This won't work as that NOTE can combine several issues in the R CMD check object.
