### ISSUE TITLE
different behaviour of check_description() and tidy_desc() in Windows

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#88]
Just a small remark which I think advanced users would certainly overlook, but it might be a nuissance for others to solve.

When I run `check_description()` locally, I get the error '_DESCRIPTION not tidy. Use `checklist::tidy_desc()`_'.  Running `checklist::tidy_desc()` indeed gives a small variation with the current situation (that passes the GHA tests): it sorts the dependencies alphabetically ignoring the difference between upper and lower case (as the Windows default is case insensitivity), whereas the GHA on Linux requires them to be sorted with upper case names first.

As I usually get alarmed by the online checks rather than running them locally, and as I'm familiar with the most important differences between Windows and Linux, I won't easily get caught by this trap, but I can imagine this could be a nuissance to solve for starting GHA and checklist users who have solved all errors locally before pushing it to github.

**Comment by ThierryO** [comment]
This should be fixed by 88c4ad82b81b4efa563b7c05421335ff71fe87a3  in #90
