### ISSUE TITLE
Malformed Zenodo metadata?

### ISSUE THREAD

**Issue by florisvdh** [inbo/checklist#89]
Just from observation at Zenodo: it seems that the description is overwritten in a new version, possibly by the content of a commit message. Also the title seems to have changed.

- old version: https://zenodo.org/record/5814814

![afbeelding](https://user-images.githubusercontent.com/19164640/172574400-9291292a-9bcb-4a28-9220-fcfbf4d7745c.png)

- new version: https://zenodo.org/record/6533084

![afbeelding](https://user-images.githubusercontent.com/19164640/172574305-0e58a146-6111-415d-a64e-2c9cd2738d17.png)

**Comment by ThierryO** [comment]
That repo doesn't have a `.zenodo.json` yet. I'm planning to write one based on the information in the `README.md` in case of a project (not a package).

- badges are optional
- version number is optional
- language information taken from default spell check language set in `checklist.yml`
- CC-BY license (license must be set).


How should we handle the upload type? Here are a few options. Create an test upload at https://sandbox.zenodo.org to see all the options.
-  software
- publication / software documentation
- publication / other
- other

## Source code of the template

```

<!-- badges: start -->
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5814813.svg)](https://doi.org/10.5281/zenodo.5814813)
![GitHub](https://img.shields.io/github/license/inbo/patrijs-steekproefkader)
![GitHub release (latest by date)](https://img.shields.io/github/v/release/inbo/patrijs-steekproefkader)
![GitHub Release Date](https://img.shields.io/github/release-date/inbo/patrijs-steekproefkader)
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/inbo/patrijs-steekproefkader/check-source)
![GitHub repo size](https://img.shields.io/github/repo-size/inbo/patrijs-steekproefkader)
<!-- badges: end -->

# Replace this with the title

[Thierry Onkelinx![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0002-1825-0097)[^INBO][^contact],
[Raïsa Carmen![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0003-1025-8702)[^INBO],
Thomas Scheppers,
Michiel Stas[^ANB]

[^INBO]: Research Institute for Nature and Forest (INBO)
[^ANB]: Agentschap Natuur en Bos
[^contact]: contactperson

<!-- copyrightholder: Research Institute for Nature and Forest -->
<!-- version: 2023.01 -->
<!-- community: inbo -->
<!-- community: second -->
<!-- abstract: start -->
Place here the abstract. It will be included in the citation metadata.
<!-- abstract: end -->

You can add more information. This will not show in the citation metadata.

```

## Rendered version of the template

---


[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5814813.svg)](https://doi.org/10.5281/zenodo.5814813)
![GitHub](https://img.shields.io/github/license/inbo/patrijs-steekproefkader)
![GitHub release (latest by date)](https://img.shields.io/github/v/release/inbo/patrijs-steekproefkader)
![GitHub Release Date](https://img.shields.io/github/release-date/inbo/patrijs-steekproefkader)
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/inbo/patrijs-steekproefkader/check-source)
![GitHub repo size](https://img.shields.io/github/repo-size/inbo/patrijs-steekproefkader)


# Replace this with the title

[Thierry Onkelinx![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0002-1825-0097)[^INBO][^contact],
[Raïsa Carmen![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0003-1025-8702)[^INBO],
Thomas Scheppers,
Michiel Stas[^ANB]

[^INBO]: Research Institute for Nature and Forest (INBO)
[^ANB]: Agentschap Natuur en Bos
[^contact]: contactperson






Place here the abstract. It will be included in the citation metadata.


You can add more information. This will not show in the citation metadata.

**Comment by ThierryO** [comment]
@inbo/bmk and @inbo/oscibio: can you give me some feedback on this. The main idea is to add a function to writes a `.zenodo.json` based on the information in the `README.md` in case of an R project. While parsing the `README.md`, we can validate the metadata at the same time.
The benefits of this:
- more complete and standardised INBO README's.
- all mandatory metadata for Zenodo is present. Making it easy to release new versions to Zenodo. E.g. by adding the repo to zenodo and automatically creating a release when pushing to the main branch. Which triggers a new version in Zenodo.
- generating a `CITATION.cff` too provides citation information on GitHub. Have a look at the main page of this repository. On the right you'll see "cite this repository".

The example below makes the copyright holder more visible compared to the example above.

---


[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5814813.svg)](https://doi.org/10.5281/zenodo.5814813)
![GitHub](https://img.shields.io/github/license/inbo/patrijs-steekproefkader)
![GitHub release (latest by date)](https://img.shields.io/github/v/release/inbo/patrijs-steekproefkader)
![GitHub Release Date](https://img.shields.io/github/release-date/inbo/patrijs-steekproefkader)
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/inbo/patrijs-steekproefkader/check-source)
![GitHub repo size](https://img.shields.io/github/repo-size/inbo/patrijs-steekproefkader)


# Replace this with the title

[Thierry Onkelinx![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0002-1825-0097)[^cp][^INBO],
[Raïsa Carmen![ORCID logo](https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png)](https://orcid.org/0000-0003-1025-8702)[^INBO],
Thomas Scheppers,
Michiel Stas[^ANB]
Research Institute for Nature and Forest[^ch]

[^INBO]: Research Institute for Nature and Forest (INBO)
[^ANB]: Agentschap Natuur en Bos
[^cp]: contact person
[^ch]: copyright holder





Place here the abstract. It will be included in the citation metadata.


You can add more information. This will not show in the citation metadata.

**Comment by peterdesmet** [comment]
@ThierryO looks cool. Can you clarify what files the function will read and what files the function will (over)write?

If the README is being overwritten, I would follow the output of `usethis::use_readme_rmd()` as much as possible. E.g. list the badges below the title.

**Comment by ThierryO** [comment]
> @ThierryO looks cool. Can you clarify what files the function will read and what files the function will (over)write?

- The function reads `README.md` in case of an R project and `DESCRIPTION` in case of an R package.
- The function overwrites `.zenodo.json` and `CITATION.cff`
- The function errors in case mandatory information is missing or malformated.

Should be enforce the same rules on `README.md` in both projects and packages? The latter would imply that the metadata in `README.md` matches with `DESCRIPTION`.

**Comment by peterdesmet** [comment]
Thanks! No, I would not enforce `README.md` and `DESCRIPTION` to match, so the formatting rules would only be there for projects. But I would try to have those formatting rules play nice with output of `usethis::use_readme_md()`

Other notes:

1. I would opt to have:

```
[author](orcid_url)[^affiliation]
author[^affiliation]
author
```

And not try to add ORCID logos.

2. I would opt for `<!-- description -->` rather than `abstract`, since that is the term used in Zenodo.

**Comment by ThierryO** [comment]
We recommend to use [`checklist::create_project()`](https://inbo.github.io/checklist/reference/create_project.html) and [`checklist::create_package()`](https://inbo.github.io/checklist/reference/create_package.html). Those functions will create an RStudio project with templates. The user chooses interactively which items to add (and check) in case of a project. In case of a package we activate the entire set of templates and checks. Use the `setup_*()` variants on existing projects and packages.
