### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/checklist#91]
When running `checklist::check_documentation()`, I got the following error message:
`` Item starts with `* ` or `    * `. Multiline items start with `  `.``

Without any context, this message was completely unclear to me, as I didn't use any '* ' in my (functions) documentation.  Only after searching this message in the source code of checklist, I discovered the message referred to the NEWS.md file.  Fortunately I used the checklist NEWS.md as an example and quickly discovered that the problem was that I didn't use indent the line after a '*'.  Because if I would have looked at the error message itself to try solving the problem, I would probably have searched a very long time to solve it, as the error message doesn't describe what is wrong, but it describes what is correct.  This is rather confusing, as I would have interpret the error message as `it is not allowed to start items with '* '`.  So I would suggest to clarify this error message:
- refer to NEWS.md to narrow the scope
- make clear that the message describes what it should be: 'Item **have to** start with ... Multiline items **have to** start with ...'

**Comment by ElsLommelen** [comment]
I tried this with the newest version of checklist (`checklist     0.3.0      2023-02-27 [1] Github (inbo/checklist@4cf8102)`), and the error (with updated error message) is still dropped if a line starts with 6 spaces.  It seems that the error message has changed but not the regex that detects the problem.  Could you please have a look at it before merging PR #94?

**Comment by ElsLommelen** [comment]
The offending `NEWS.md` can be downloaded [here](https://github.com/inbo/dhcurve/blob/minor-changes/NEWS.md).

**Comment by ThierryO** [comment]
Should be fixed in 97a0a31

**Comment by ElsLommelen** [comment]
The error is indeed gone.  Thank you!
